spring :
  datasource:
    url: jdbc:mariadb://localhost:3306/school-management-system
    username: root
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true